#!/bin/bash

Rscript --vanilla ./pkg_install.R

wget "https://data.sfgov.org/api/views/vw6y-z8j6/rows.csv?accessType=DOWNLOAD" -O SF_311_Case_Data.csv

Rscript --vanilla ./process_SF_case_data.R SF_311_Case_Data.csv